### ISSUE TITLE
Make to_buffer pub

### ISSUE THREAD

**Issue by griccardos** [psiphi75/sonogram#11]
It will be useful to have `Spectrogram.to_buffer` public, as sometimes one would like to acess the data without saving to a file.
I currently need the db values as the `to_csv` provides, so i need to write to file, then read from file again.
Would be better if i just had the raw db values in a buffer.

**Comment by psiphi75** [comment]
Yes, you are right, it would make sense to expose `to_buffer`.  Feel free to create a PR for this.
