### ISSUE TITLE
Better handling of multiple audio channels

### ISSUE THREAD

**Issue by ijoseph** [psiphi75/sonogram#3]
In some sense, this is just making the TODO into a github issue. https://github.com/psiphi75/sonogram/blob/5e71fc2337f9c17ba620f09e6adc363683bb8953/src/spectrograph.rs#L112-L113

I ran into this. I was able to workaround with `ffmpeg`'s `-ac` flag: 

```bash
IN_FILE='some_audio_file.extension'
ffmpeg -i $IN_FILE -ac 1 "${IN_FILE}.wav"

sonogram --wav "${IN_FILE}.wav" -p out.png
```

 but would be nice to have a better solution. Probably, in order of effort and value:
1. More clear error, with the suggestion to use `ffmepg` as above
2. Warning, and select a channel at random
3. Use both channels and display both.

**Comment by psiphi75** [comment]
Hi, I have fixed this.  The audio channel will default to 1.  But you can change this using the shiny new `--channel <NUM>` option.
